// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwxczjqtalcdjtnfckjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eGN6anF0YWxjZGp0bmZja2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTkxNTUsImV4cCI6MjA2ODY3NTE1NX0.saGNuWX80zXsl5spOyJSf5gvUsVUlNPDz_1g2yImx7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});